name: Nine Labs
description: Strategic Thinking to Help Your Business.
url: https://ninelabs.com
markdown: kramdown
redcarpet:
  extensions: [smart]
exclude: [vendor]
highlighter: pygments
permalink: /notes/:title.html
paginate: 100
paginate_path: "/notes/page:num/"
gems:
  - jekyll-redirect-from

page_gen:
  - data: 'jobs'
    template: 'job-posting'
    name: 'title'
    dir: 'jobs'
  - data: 'team'
    template: 'team-member-bio'
    name: 'name'
    dir: 'about'
