name: Nine Labs
description: Strategic Thinking to Help Your Business.
url: https://ninelabs.com
markdown: redcarpet
redcarpet:
  extensions: [smart]

highlighter: pygments
port: 9999
permalink: /notes/:title.html
paginate: 100
paginate_path: "/notes/page:num/"
gems:
  - jekyll-redirect-from